version: '3.8'

services:
  php:
    build: .
    container_name: php-cli-container
    volumes:
      - .:/KataCheckout
    working_dir: /KataCheckout
    command: sh -c "composer install --prefer-dist && composer dump-autoload && tail -f /dev/null"
    environment:
      - PHP_INI_DISPLAY_ERRORS=1
      - PHP_INI_MEMORY_LIMIT=512M
